packages:
  - apps/*
  - packages/*

catalogs:
  prisma:
    prisma: latest

ignoredBuiltDependencies:
  - fsevents

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - cypress
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

preferFrozenLockfile: true

sideEffectsCache: true
